// PrivacyPolicy.tsx
import React from 'react';
import { ScrollView, View, Text, StyleSheet, Linking, Pressable } from 'react-native';

const H1: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text accessibilityRole="header" style={styles.h1}>
    {children}
  </Text>
);
const H2: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text accessibilityRole="header" style={styles.h2}>
    {children}
  </Text>
);
const P: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Text style={styles.p}>{children}</Text>
);
const Li: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <View style={styles.liRow}>
    <Text style={styles.bullet}>•</Text>
    <Text style={styles.li}>{children}</Text>
  </View>
);
const A: React.FC<{ href: string; children: React.ReactNode }> = ({ href, children }) => (
  <Pressable onPress={() => Linking.openURL(href)} accessibilityRole="link">
    <Text style={styles.link}>{children}</Text>
  </Pressable>
);

export default function PrivacyPolicy() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>Privacy Policy for Just Some Kana</Text>
      <H1>Privacy Policy</H1>
      <P>Last updated: February 06, 2023</P>
      <P>
        This Privacy Policy describes our policies and procedures on the collection, use, and
        disclosure of your information when you use the Service and tells you about your privacy
        rights and how the law protects you.
      </P>
      <P>
        We use your personal data to provide and improve the Service. By using the Service, you
        agree to the collection and use of information in accordance with this Privacy Policy. This
        Privacy Policy was created with the help of the{' '}
        <A href="https://www.termsfeed.com/privacy-policy-generator/">
          TermsFeed Privacy Policy Generator
        </A>
        .
      </P>

      <H1>Interpretation and Definitions</H1>
      <H2>Interpretation</H2>
      <P>
        Words with initial capital letters have meanings defined under the following conditions. The
        following definitions shall have the same meaning whether they appear in singular or plural.
      </P>

      <H2>Definitions</H2>
      <P>For the purposes of this Privacy Policy:</P>
      <Li>
        <Text>
          <Text style={styles.bold}>Account</Text> means a unique account created for you to access
          our Service or parts of our Service.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Affiliate</Text> means an entity that controls, is controlled
          by, or is under common control with a party, where “control” means ownership of 50% or
          more of the shares, equity interest, or other securities entitled to vote for election of
          directors or other managing authority.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Application</Text> refers to Just Some Kana, the software
          program provided by the Company.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Company</Text> (“the Company”, “We”, “Us”, or “Our”) refers to
          Just Some Kana.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Country</Text> refers to: Ohio, United States.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Device</Text> means any device that can access the Service such
          as a computer, cellphone, or digital tablet.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Personal Data</Text> is any information that relates to an
          identified or identifiable individual.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Service</Text> refers to the Application.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Service Provider</Text> means any natural or legal person who
          processes the data on behalf of the Company.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>Usage Data</Text> refers to data collected automatically, either
          generated by the use of the Service or from the Service infrastructure itself.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>You</Text> means the individual using the Service, or the
          company or other legal entity on whose behalf the individual is using the Service.
        </Text>
      </Li>

      <H1>Collecting and Using Your Personal Data</H1>
      <H2>Types of Data Collected</H2>
      <H2>Personal Data</H2>
      <P>
        While using our Service, we may ask you to provide certain personally identifiable
        information that can be used to contact or identify you. Personally identifiable information
        may include, but is not limited to:
      </P>
      <Li>Usage Data</Li>

      <H2>Usage Data</H2>
      <P>Usage Data is collected automatically when using the Service.</P>
      <P>
        Usage Data may include information such as your device’s IP address, browser type and
        version, pages visited, time and date of visit, time spent on pages, unique device
        identifiers, and other diagnostic data. When you access the Service via a mobile device,
        this may include your device type, unique ID, IP address, operating system, mobile browser
        type, unique identifiers, and diagnostic data.
      </P>

      <H2>Use of Your Personal Data</H2>
      <P>The Company may use Personal Data for the following purposes:</P>
      <Li>
        <Text>
          <Text style={styles.bold}>To provide and maintain our Service</Text>, including to monitor
          usage.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>To manage your Account</Text> as a registered user.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>For the performance of a contract</Text> you have with us.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>To contact you</Text> (email, calls, SMS, push notifications)
          regarding updates or informational communications.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>To provide you</Text> with news, special offers, and general
          information about goods, services, and events similar to those you already purchased or
          inquired about (unless you opt out).
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>To manage your requests</Text> to us.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>For business transfers</Text> including mergers, acquisitions,
          or sales of assets.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>For other purposes</Text> such as data analysis, usage trends,
          campaign effectiveness, and service improvement.
        </Text>
      </Li>

      <P>We may share your personal information in the following situations:</P>
      <Li>
        <Text>
          <Text style={styles.bold}>With Service Providers</Text> to monitor and analyze use of our
          Service or to contact you.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>For business transfers</Text> related to mergers, asset sales,
          financing, or acquisitions.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>With Affiliates</Text> who must honor this Privacy Policy.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>With business partners</Text> to offer certain products,
          services, or promotions.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>With other users</Text> in public areas of the Service.
        </Text>
      </Li>
      <Li>
        <Text>
          <Text style={styles.bold}>With your consent</Text> for any other purpose you approve.
        </Text>
      </Li>

      <H2>Retention of Your Personal Data</H2>
      <P>
        The Company will retain Personal Data only as long as necessary for the purposes in this
        Privacy Policy and to comply with legal obligations, resolve disputes, and enforce
        agreements. Usage Data is retained for shorter periods unless needed to improve security or
        functionality, or if legally required to retain it longer.
      </P>

      <H2>Transfer of Your Personal Data</H2>
      <P>
        Your information may be transferred to—and maintained on—computers outside your
        jurisdiction, where data protection laws may differ. We will take reasonable steps to ensure
        data is treated securely and no transfer occurs without adequate controls in place.
      </P>

      <H2>Delete Your Personal Data</H2>
      <P>
        You have the right to delete or request deletion of Personal Data we have collected about
        you.
      </P>
      <P>
        The Service may allow deleting certain information from within your account. You can also
        sign in to manage your personal information or contact us to request access, correction, or
        deletion. We may retain some information where we have a legal obligation or lawful basis.
      </P>

      <H2>Disclosure of Your Personal Data</H2>
      <H2>Business Transactions</H2>
      <P>
        If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may
        be transferred with prior notice.
      </P>

      <H2>Law Enforcement</H2>
      <P>
        Under certain circumstances, we may be required to disclose your Personal Data to comply
        with law or valid public authority requests.
      </P>

      <H2>Other Legal Requirements</H2>
      <P>The Company may disclose Personal Data in good faith when necessary to:</P>
      <Li>Comply with a legal obligation</Li>
      <Li>Protect and defend the Company’s rights or property</Li>
      <Li>Prevent or investigate possible wrongdoing in connection with the Service</Li>
      <Li>Protect the personal safety of users or the public</Li>
      <Li>Protect against legal liability</Li>

      <H2>Security of Your Personal Data</H2>
      <P>
        We strive to use commercially acceptable means to protect Personal Data, but no method of
        transmission or electronic storage is 100% secure.
      </P>

      <H1>Children’s Privacy</H1>
      <P>
        Our Service does not address anyone under 13. We do not knowingly collect personally
        identifiable information from anyone under 13. If you are a parent/guardian and become aware
        your child has provided Personal Data, contact us so we can remove it. Where parental
        consent is required by law, we may require it before processing.
      </P>

      <H1>Links to Other Websites</H1>
      <P>
        Our Service may contain links to third-party sites not operated by us. We strongly advise
        you to review the privacy policy of every site you visit. We have no control over and assume
        no responsibility for their content or practices.
      </P>

      <H1>Changes to this Privacy Policy</H1>
      <P>
        We may update this Privacy Policy from time to time. We will notify you by posting the new
        Privacy Policy on this page and, where appropriate, via email and/or a prominent notice on
        our Service prior to the change becoming effective. The “Last updated” date will be revised
        accordingly.
      </P>

      <H1>Contact Us</H1>
      <P>If you have questions about this Privacy Policy, you can contact us:</P>
      <Li>
        By email:{' '}
        {/* The source file used Cloudflare email protection; replace with your actual contact email */}
        <A href="mailto:contact@example.com">contact@example.com</A>
      </Li>

      <View style={{ height: 32 }} />
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 16,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 12,
  },
  h1: {
    fontSize: 20,
    fontWeight: '700',
    marginTop: 16,
    marginBottom: 8,
  },
  h2: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 14,
    marginBottom: 6,
  },
  p: {
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 10,
  },
  bold: {
    fontWeight: '700',
  },
  liRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  bullet: {
    fontSize: 16,
    lineHeight: 22,
    marginRight: 8,
  },
  li: {
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
  },
  link: {
    textDecorationLine: 'underline',
  },
});
