name: Build Preview

jobs:
  build_ios:
    type: build
    params:
      platform: ios # required
      profile: preview
  build_android:
    type: build
    params:
      platform: ios # required
      profile: preview
  deploy_web:
    needs: [build_ios, build_android] # only update website if builds are successful
    type: deploy