name: Build Preview on Main on push

on:
  # Trigger on pushes to main branch
  push:
    branches: [main]

jobs:
  build_ios:
    type: build
    params:
      platform: ios # required
      profile: preview
  build_android:
    type: build
    params:
      platform: android # required
      profile: preview