name: Create development builds

jobs:
  ios_simulator_development_build:
    name: Build iOS simulator
    type: build
    params:
      platform: ios
      profile: development:simulator
  android_development_build:
    name: Build Android
    needs: [ios_simulator_development_build] # canary / coal mine
    type: build
    params:
      platform: android
      profile: development
  ios_device_development_build:
    name: Build iOS device
    needs: [ios_simulator_development_build]
    type: build
    params:
      platform: ios
      profile: development
