name: Publish PR preview update

on:
  pull_request:
    branches: ['*']

jobs:
  run_unit_tests:
    name: Run unit tests
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run: npx bun test

  publish_preview_update:
    name: Publish update to ${{ github.ref_name || 'test' }} branch
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
  comment_on_pr:
    name: Post Results to PR
    after: [publish_preview_update]
    type: github-comment