name: Publish PR preview update

on:
  pull_request:
    branches: ['*']

jobs:
  run_unit_tests:
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run: npx bun test

  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}