name: Test

on: [pull_request]

jobs:
  ci:
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      checks: write
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn

      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          continue_on_error: false
          git_name: EcoBot

      - name: jest test with Coverage
        continue-on-error: true
        working-directory: '' 
        run: yarn test --json --outputFile=jest-results.json

      - name: Process jest results with default
        if: always()
        # You may also reference just the major or major.minor version
        uses: im-open/process-jest-test-results@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: './jest-results.json'
          git_name: EcoBot
          create-pr-comment: true